
services:
  django:
    build: .
    ports:
      - "8000:8000"
    networks:
      - gateway

  krakend:
    image: devopsfaith/krakend:latest
    container_name: krakend
    ports:
      - "8082:8080"
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    networks:
      - gateway
    depends_on:
      - django
    environment:
      - BACKEND_URL=https://127.0.0.1:8000

networks:
  gateway:
    driver: bridge
