# Generated by Django 5.1.2 on 2024-10-17 09:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emnaMensajesMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('es_activo', models.BooleanField(default=True)),
                ('vigencia', models.DateTimeField(blank=True, null=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diarios', to='emnaMensajesMS.conversacion')),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(max_length=250)),
                ('es_temporal', models.BooleanField(default=False)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='emnaSeguridadMS.diario')),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='emnaMensajesMS.mensaje')),
            ],
        ),
    ]
