# Generated by Django 5.1.2 on 2024-10-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emnaSeguridadMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='contenido',
            field=models.TextField(max_length=500),
        ),
    ]
