# Generated by Django 5.1.2 on 2024-10-17 09:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emnaMensajesMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInvitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TipoNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('clave', models.CharField(max_length=128)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('es_activo', models.BooleanField(default=True)),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='emnaUsuariosMS.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('es_leido', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('es_aceptado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='emnaUsuariosMS.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_invitado', models.EmailField(max_length=254, unique=True)),
                ('mensaje_personalizado', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('es_aceptado', models.BooleanField(default=False)),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitados', to='emnaMensajesMS.conversacion')),
                ('tipo_invitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='emnaUsuariosMS.tipoinvitacion')),
                ('usuario_envia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emisor', to='emnaUsuariosMS.usuario')),
            ],
        ),
    ]
