# Generated by Django 5.1.2 on 2024-11-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emnaUsuariosMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Clave Encriptada', 'verbose_name_plural': 'Claves Encriptadas'},
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='clave',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
