# Generated by Django 5.1.2 on 2024-10-31 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emnaMensajesMS', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversacion',
            old_name='diario',
            new_name='descripcion',
        ),
    ]
