# Generated by Django 5.1.2 on 2024-11-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emnaMensajesMS', '0003_rename_diario_conversacion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversacion',
            name='fecha_conversacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
